// Static country reference data (name, ISO 3166-1 alpha-2 code, default ISO
// 4217 currency, and international dial code) for the registration form's
// Country field and the currency-from-region feature. Generated once from
// the 'world-countries' package (UN member / independent states only, with a
// couple of manual currency overrides for countries whose dataset entry
// lists several legal-tender currencies with no flagged primary one) and
// checked in as plain data so the app has no runtime dependency on it.
export type Country = { name: string; code: string; currency: string | null; dial: string };

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", currency: "AFN", dial: "+93" },
  { name: "Albania", code: "AL", currency: "ALL", dial: "+355" },
  { name: "Algeria", code: "DZ", currency: "DZD", dial: "+213" },
  { name: "Andorra", code: "AD", currency: "EUR", dial: "+376" },
  { name: "Angola", code: "AO", currency: "AOA", dial: "+244" },
  { name: "Antigua and Barbuda", code: "AG", currency: "XCD", dial: "+1268" },
  { name: "Argentina", code: "AR", currency: "ARS", dial: "+54" },
  { name: "Armenia", code: "AM", currency: "AMD", dial: "+374" },
  { name: "Australia", code: "AU", currency: "AUD", dial: "+61" },
  { name: "Austria", code: "AT", currency: "EUR", dial: "+43" },
  { name: "Azerbaijan", code: "AZ", currency: "AZN", dial: "+994" },
  { name: "Bahamas", code: "BS", currency: "BSD", dial: "+1242" },
  { name: "Bahrain", code: "BH", currency: "BHD", dial: "+973" },
  { name: "Bangladesh", code: "BD", currency: "BDT", dial: "+880" },
  { name: "Barbados", code: "BB", currency: "BBD", dial: "+1246" },
  { name: "Belarus", code: "BY", currency: "BYN", dial: "+375" },
  { name: "Belgium", code: "BE", currency: "EUR", dial: "+32" },
  { name: "Belize", code: "BZ", currency: "BZD", dial: "+501" },
  { name: "Benin", code: "BJ", currency: "XOF", dial: "+229" },
  { name: "Bhutan", code: "BT", currency: "BTN", dial: "+975" },
  { name: "Bolivia", code: "BO", currency: "BOB", dial: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM", dial: "+387" },
  { name: "Botswana", code: "BW", currency: "BWP", dial: "+267" },
  { name: "Brazil", code: "BR", currency: "BRL", dial: "+55" },
  { name: "Brunei", code: "BN", currency: "BND", dial: "+673" },
  { name: "Bulgaria", code: "BG", currency: "BGN", dial: "+359" },
  { name: "Burkina Faso", code: "BF", currency: "XOF", dial: "+226" },
  { name: "Burundi", code: "BI", currency: "BIF", dial: "+257" },
  { name: "Cambodia", code: "KH", currency: "KHR", dial: "+855" },
  { name: "Cameroon", code: "CM", currency: "XAF", dial: "+237" },
  { name: "Canada", code: "CA", currency: "CAD", dial: "+1" },
  { name: "Cape Verde", code: "CV", currency: "CVE", dial: "+238" },
  { name: "Central African Republic", code: "CF", currency: "XAF", dial: "+236" },
  { name: "Chad", code: "TD", currency: "XAF", dial: "+235" },
  { name: "Chile", code: "CL", currency: "CLP", dial: "+56" },
  { name: "China", code: "CN", currency: "CNY", dial: "+86" },
  { name: "Colombia", code: "CO", currency: "COP", dial: "+57" },
  { name: "Comoros", code: "KM", currency: "KMF", dial: "+269" },
  { name: "Costa Rica", code: "CR", currency: "CRC", dial: "+506" },
  { name: "Croatia", code: "HR", currency: "EUR", dial: "+385" },
  { name: "Cuba", code: "CU", currency: "CUP", dial: "+53" },
  { name: "Cyprus", code: "CY", currency: "EUR", dial: "+357" },
  { name: "Czechia", code: "CZ", currency: "CZK", dial: "+420" },
  { name: "Denmark", code: "DK", currency: "DKK", dial: "+45" },
  { name: "Djibouti", code: "DJ", currency: "DJF", dial: "+253" },
  { name: "Dominica", code: "DM", currency: "XCD", dial: "+1767" },
  { name: "Dominican Republic", code: "DO", currency: "DOP", dial: "+1" },
  { name: "DR Congo", code: "CD", currency: "CDF", dial: "+243" },
  { name: "Ecuador", code: "EC", currency: "USD", dial: "+593" },
  { name: "Egypt", code: "EG", currency: "EGP", dial: "+20" },
  { name: "El Salvador", code: "SV", currency: "USD", dial: "+503" },
  { name: "Equatorial Guinea", code: "GQ", currency: "XAF", dial: "+240" },
  { name: "Eritrea", code: "ER", currency: "ERN", dial: "+291" },
  { name: "Estonia", code: "EE", currency: "EUR", dial: "+372" },
  { name: "Eswatini", code: "SZ", currency: "SZL", dial: "+268" },
  { name: "Ethiopia", code: "ET", currency: "ETB", dial: "+251" },
  { name: "Fiji", code: "FJ", currency: "FJD", dial: "+679" },
  { name: "Finland", code: "FI", currency: "EUR", dial: "+358" },
  { name: "France", code: "FR", currency: "EUR", dial: "+33" },
  { name: "Gabon", code: "GA", currency: "XAF", dial: "+241" },
  { name: "Gambia", code: "GM", currency: "GMD", dial: "+220" },
  { name: "Georgia", code: "GE", currency: "GEL", dial: "+995" },
  { name: "Germany", code: "DE", currency: "EUR", dial: "+49" },
  { name: "Ghana", code: "GH", currency: "GHS", dial: "+233" },
  { name: "Greece", code: "GR", currency: "EUR", dial: "+30" },
  { name: "Grenada", code: "GD", currency: "XCD", dial: "+1473" },
  { name: "Guatemala", code: "GT", currency: "GTQ", dial: "+502" },
  { name: "Guinea", code: "GN", currency: "GNF", dial: "+224" },
  { name: "Guinea-Bissau", code: "GW", currency: "XOF", dial: "+245" },
  { name: "Guyana", code: "GY", currency: "GYD", dial: "+592" },
  { name: "Haiti", code: "HT", currency: "HTG", dial: "+509" },
  { name: "Honduras", code: "HN", currency: "HNL", dial: "+504" },
  { name: "Hungary", code: "HU", currency: "HUF", dial: "+36" },
  { name: "Iceland", code: "IS", currency: "ISK", dial: "+354" },
  { name: "India", code: "IN", currency: "INR", dial: "+91" },
  { name: "Indonesia", code: "ID", currency: "IDR", dial: "+62" },
  { name: "Iran", code: "IR", currency: "IRR", dial: "+98" },
  { name: "Iraq", code: "IQ", currency: "IQD", dial: "+964" },
  { name: "Ireland", code: "IE", currency: "EUR", dial: "+353" },
  { name: "Israel", code: "IL", currency: "ILS", dial: "+972" },
  { name: "Italy", code: "IT", currency: "EUR", dial: "+39" },
  { name: "Ivory Coast", code: "CI", currency: "XOF", dial: "+225" },
  { name: "Jamaica", code: "JM", currency: "JMD", dial: "+1876" },
  { name: "Japan", code: "JP", currency: "JPY", dial: "+81" },
  { name: "Jordan", code: "JO", currency: "JOD", dial: "+962" },
  { name: "Kazakhstan", code: "KZ", currency: "KZT", dial: "+7" },
  { name: "Kenya", code: "KE", currency: "KES", dial: "+254" },
  { name: "Kiribati", code: "KI", currency: "AUD", dial: "+686" },
  { name: "Kuwait", code: "KW", currency: "KWD", dial: "+965" },
  { name: "Kyrgyzstan", code: "KG", currency: "KGS", dial: "+996" },
  { name: "Laos", code: "LA", currency: "LAK", dial: "+856" },
  { name: "Latvia", code: "LV", currency: "EUR", dial: "+371" },
  { name: "Lebanon", code: "LB", currency: "LBP", dial: "+961" },
  { name: "Lesotho", code: "LS", currency: "LSL", dial: "+266" },
  { name: "Liberia", code: "LR", currency: "LRD", dial: "+231" },
  { name: "Libya", code: "LY", currency: "LYD", dial: "+218" },
  { name: "Liechtenstein", code: "LI", currency: "CHF", dial: "+423" },
  { name: "Lithuania", code: "LT", currency: "EUR", dial: "+370" },
  { name: "Luxembourg", code: "LU", currency: "EUR", dial: "+352" },
  { name: "Madagascar", code: "MG", currency: "MGA", dial: "+261" },
  { name: "Malawi", code: "MW", currency: "MWK", dial: "+265" },
  { name: "Malaysia", code: "MY", currency: "MYR", dial: "+60" },
  { name: "Maldives", code: "MV", currency: "MVR", dial: "+960" },
  { name: "Mali", code: "ML", currency: "XOF", dial: "+223" },
  { name: "Malta", code: "MT", currency: "EUR", dial: "+356" },
  { name: "Marshall Islands", code: "MH", currency: "USD", dial: "+692" },
  { name: "Mauritania", code: "MR", currency: "MRU", dial: "+222" },
  { name: "Mauritius", code: "MU", currency: "MUR", dial: "+230" },
  { name: "Mexico", code: "MX", currency: "MXN", dial: "+52" },
  { name: "Micronesia", code: "FM", currency: null, dial: "+691" },
  { name: "Moldova", code: "MD", currency: "MDL", dial: "+373" },
  { name: "Monaco", code: "MC", currency: "EUR", dial: "+377" },
  { name: "Mongolia", code: "MN", currency: "MNT", dial: "+976" },
  { name: "Montenegro", code: "ME", currency: "EUR", dial: "+382" },
  { name: "Morocco", code: "MA", currency: "MAD", dial: "+212" },
  { name: "Mozambique", code: "MZ", currency: "MZN", dial: "+258" },
  { name: "Myanmar", code: "MM", currency: "MMK", dial: "+95" },
  { name: "Namibia", code: "NA", currency: "NAD", dial: "+264" },
  { name: "Nauru", code: "NR", currency: "AUD", dial: "+674" },
  { name: "Nepal", code: "NP", currency: "NPR", dial: "+977" },
  { name: "Netherlands", code: "NL", currency: "EUR", dial: "+31" },
  { name: "New Zealand", code: "NZ", currency: "NZD", dial: "+64" },
  { name: "Nicaragua", code: "NI", currency: "NIO", dial: "+505" },
  { name: "Niger", code: "NE", currency: "XOF", dial: "+227" },
  { name: "Nigeria", code: "NG", currency: "NGN", dial: "+234" },
  { name: "North Korea", code: "KP", currency: "KPW", dial: "+850" },
  { name: "North Macedonia", code: "MK", currency: "MKD", dial: "+389" },
  { name: "Norway", code: "NO", currency: "NOK", dial: "+47" },
  { name: "Oman", code: "OM", currency: "OMR", dial: "+968" },
  { name: "Pakistan", code: "PK", currency: "PKR", dial: "+92" },
  { name: "Palau", code: "PW", currency: "USD", dial: "+680" },
  { name: "Panama", code: "PA", currency: "PAB", dial: "+507" },
  { name: "Papua New Guinea", code: "PG", currency: "PGK", dial: "+675" },
  { name: "Paraguay", code: "PY", currency: "PYG", dial: "+595" },
  { name: "Peru", code: "PE", currency: "PEN", dial: "+51" },
  { name: "Philippines", code: "PH", currency: "PHP", dial: "+63" },
  { name: "Poland", code: "PL", currency: "PLN", dial: "+48" },
  { name: "Portugal", code: "PT", currency: "EUR", dial: "+351" },
  { name: "Qatar", code: "QA", currency: "QAR", dial: "+974" },
  { name: "Republic of the Congo", code: "CG", currency: "XAF", dial: "+242" },
  { name: "Romania", code: "RO", currency: "RON", dial: "+40" },
  { name: "Russia", code: "RU", currency: "RUB", dial: "+7" },
  { name: "Rwanda", code: "RW", currency: "RWF", dial: "+250" },
  { name: "Saint Kitts and Nevis", code: "KN", currency: "XCD", dial: "+1869" },
  { name: "Saint Lucia", code: "LC", currency: "XCD", dial: "+1758" },
  { name: "Saint Vincent and the Grenadines", code: "VC", currency: "XCD", dial: "+1784" },
  { name: "Samoa", code: "WS", currency: "WST", dial: "+685" },
  { name: "San Marino", code: "SM", currency: "EUR", dial: "+378" },
  { name: "São Tomé and Príncipe", code: "ST", currency: "STN", dial: "+239" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", dial: "+966" },
  { name: "Senegal", code: "SN", currency: "XOF", dial: "+221" },
  { name: "Serbia", code: "RS", currency: "RSD", dial: "+381" },
  { name: "Seychelles", code: "SC", currency: "SCR", dial: "+248" },
  { name: "Sierra Leone", code: "SL", currency: "SLL", dial: "+232" },
  { name: "Singapore", code: "SG", currency: "SGD", dial: "+65" },
  { name: "Slovakia", code: "SK", currency: "EUR", dial: "+421" },
  { name: "Slovenia", code: "SI", currency: "EUR", dial: "+386" },
  { name: "Solomon Islands", code: "SB", currency: "SBD", dial: "+677" },
  { name: "Somalia", code: "SO", currency: "SOS", dial: "+252" },
  { name: "South Africa", code: "ZA", currency: "ZAR", dial: "+27" },
  { name: "South Korea", code: "KR", currency: "KRW", dial: "+82" },
  { name: "South Sudan", code: "SS", currency: "SSP", dial: "+211" },
  { name: "Spain", code: "ES", currency: "EUR", dial: "+34" },
  { name: "Sri Lanka", code: "LK", currency: "LKR", dial: "+94" },
  { name: "Sudan", code: "SD", currency: "SDG", dial: "+249" },
  { name: "Suriname", code: "SR", currency: "SRD", dial: "+597" },
  { name: "Sweden", code: "SE", currency: "SEK", dial: "+46" },
  { name: "Switzerland", code: "CH", currency: "CHF", dial: "+41" },
  { name: "Syria", code: "SY", currency: "SYP", dial: "+963" },
  { name: "Tajikistan", code: "TJ", currency: "TJS", dial: "+992" },
  { name: "Tanzania", code: "TZ", currency: "TZS", dial: "+255" },
  { name: "Thailand", code: "TH", currency: "THB", dial: "+66" },
  { name: "Timor-Leste", code: "TL", currency: "USD", dial: "+670" },
  { name: "Togo", code: "TG", currency: "XOF", dial: "+228" },
  { name: "Tonga", code: "TO", currency: "TOP", dial: "+676" },
  { name: "Trinidad and Tobago", code: "TT", currency: "TTD", dial: "+1868" },
  { name: "Tunisia", code: "TN", currency: "TND", dial: "+216" },
  { name: "Türkiye", code: "TR", currency: "TRY", dial: "+90" },
  { name: "Turkmenistan", code: "TM", currency: "TMT", dial: "+993" },
  { name: "Tuvalu", code: "TV", currency: "AUD", dial: "+688" },
  { name: "Uganda", code: "UG", currency: "UGX", dial: "+256" },
  { name: "Ukraine", code: "UA", currency: "UAH", dial: "+380" },
  { name: "United Arab Emirates", code: "AE", currency: "AED", dial: "+971" },
  { name: "United Kingdom", code: "GB", currency: "GBP", dial: "+44" },
  { name: "United States", code: "US", currency: "USD", dial: "+1" },
  { name: "Uruguay", code: "UY", currency: "UYU", dial: "+598" },
  { name: "Uzbekistan", code: "UZ", currency: "UZS", dial: "+998" },
  { name: "Vanuatu", code: "VU", currency: "VUV", dial: "+678" },
  { name: "Vatican City", code: "VA", currency: "EUR", dial: "+3" },
  { name: "Venezuela", code: "VE", currency: "VES", dial: "+58" },
  { name: "Vietnam", code: "VN", currency: "VND", dial: "+84" },
  { name: "Yemen", code: "YE", currency: "YER", dial: "+967" },
  { name: "Zambia", code: "ZM", currency: "ZMW", dial: "+260" },
  { name: "Zimbabwe", code: "ZW", currency: "USD", dial: "+263" },
];

export const countryByCode = (code: string | null | undefined): Country | undefined =>
  COUNTRIES.find((c) => c.code === (code ?? '').toUpperCase());

// Best-effort ISO 4217 currency code for a country; falls back to USD.
export const currencyForCountry = (code: string | null | undefined): string =>
  countryByCode(code)?.currency ?? 'USD';
