// Country reference data used across the app: registration/profile forms
// (dial code + local currency suggestion) and admin-curated trader/bot
// profile cards (a flag badge derived from the ISO code). Kept in one file
// so every feature shares the same country list instead of drifting.

export type CountryInfo = { code: string; name: string; dial: number; currency: string; flag: string };

// Converts a two-letter ISO code (e.g. "NG") into its flag emoji (e.g. "🇳🇬")
// by mapping each letter to the Unicode "regional indicator symbol" block.
export function flagEmoji(code: string): string {
  const upper = code.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return "🏳️";
  return String.fromCodePoint(...[...upper].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

const COUNTRY_DATA: { code: string; name: string; dial: number; currency: string }[] = [
  { code: "AF", name: "Afghanistan", dial: 93, currency: "AFN" },
  { code: "AL", name: "Albania", dial: 355, currency: "ALL" },
  { code: "DZ", name: "Algeria", dial: 213, currency: "DZD" },
  { code: "AS", name: "American Samoa", dial: 1, currency: "USD" },
  { code: "AD", name: "Andorra", dial: 376, currency: "EUR" },
  { code: "AO", name: "Angola", dial: 244, currency: "AOA" },
  { code: "AI", name: "Anguilla", dial: 1, currency: "XCD" },
  { code: "AG", name: "Antigua and Barbuda", dial: 1, currency: "XCD" },
  { code: "AR", name: "Argentina", dial: 54, currency: "ARS" },
  { code: "AM", name: "Armenia", dial: 374, currency: "AMD" },
  { code: "AW", name: "Aruba", dial: 297, currency: "AWG" },
  { code: "AU", name: "Australia", dial: 61, currency: "AUD" },
  { code: "AT", name: "Austria", dial: 43, currency: "EUR" },
  { code: "AZ", name: "Azerbaijan", dial: 994, currency: "AZN" },
  { code: "BS", name: "Bahamas", dial: 1, currency: "BSD" },
  { code: "BH", name: "Bahrain", dial: 973, currency: "BHD" },
  { code: "BD", name: "Bangladesh", dial: 880, currency: "BDT" },
  { code: "BB", name: "Barbados", dial: 1, currency: "BBD" },
  { code: "BY", name: "Belarus", dial: 375, currency: "BYN" },
  { code: "BE", name: "Belgium", dial: 32, currency: "EUR" },
  { code: "BZ", name: "Belize", dial: 501, currency: "BZD" },
  { code: "BJ", name: "Benin", dial: 229, currency: "XOF" },
  { code: "BM", name: "Bermuda", dial: 1, currency: "BMD" },
  { code: "BT", name: "Bhutan", dial: 975, currency: "INR" },
  { code: "BO", name: "Bolivia, Plurinational State of", dial: 591, currency: "BOB" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", dial: 599, currency: "USD" },
  { code: "BA", name: "Bosnia and Herzegovina", dial: 387, currency: "BAM" },
  { code: "BW", name: "Botswana", dial: 267, currency: "BWP" },
  { code: "BR", name: "Brazil", dial: 55, currency: "BRL" },
  { code: "IO", name: "British Indian Ocean Territory", dial: 246, currency: "USD" },
  { code: "BN", name: "Brunei Darussalam", dial: 673, currency: "BND" },
  { code: "BG", name: "Bulgaria", dial: 359, currency: "BGN" },
  { code: "BF", name: "Burkina Faso", dial: 226, currency: "XOF" },
  { code: "BI", name: "Burundi", dial: 257, currency: "BIF" },
  { code: "CV", name: "Cabo Verde", dial: 238, currency: "CVE" },
  { code: "KH", name: "Cambodia", dial: 855, currency: "KHR" },
  { code: "CM", name: "Cameroon", dial: 237, currency: "XAF" },
  { code: "CA", name: "Canada", dial: 1, currency: "CAD" },
  { code: "KY", name: "Cayman Islands", dial: 1, currency: "KYD" },
  { code: "CF", name: "Central African Republic", dial: 236, currency: "XAF" },
  { code: "TD", name: "Chad", dial: 235, currency: "XAF" },
  { code: "CL", name: "Chile", dial: 56, currency: "CLP" },
  { code: "CN", name: "China", dial: 86, currency: "CNY" },
  { code: "CX", name: "Christmas Island", dial: 61, currency: "AUD" },
  { code: "CC", name: "Cocos (Keeling) Islands", dial: 61, currency: "AUD" },
  { code: "CO", name: "Colombia", dial: 57, currency: "COP" },
  { code: "KM", name: "Comoros", dial: 269, currency: "KMF" },
  { code: "CG", name: "Congo", dial: 242, currency: "XAF" },
  { code: "CD", name: "Congo, The Democratic Republic of the", dial: 243, currency: "CDF" },
  { code: "CK", name: "Cook Islands", dial: 682, currency: "NZD" },
  { code: "CR", name: "Costa Rica", dial: 506, currency: "CRC" },
  { code: "HR", name: "Croatia", dial: 385, currency: "EUR" },
  { code: "CU", name: "Cuba", dial: 53, currency: "CUP" },
  { code: "CW", name: "Curaçao", dial: 599, currency: "XCG" },
  { code: "CY", name: "Cyprus", dial: 357, currency: "EUR" },
  { code: "CZ", name: "Czechia", dial: 420, currency: "CZK" },
  { code: "CI", name: "Côte d'Ivoire", dial: 225, currency: "XOF" },
  { code: "DK", name: "Denmark", dial: 45, currency: "DKK" },
  { code: "DJ", name: "Djibouti", dial: 253, currency: "DJF" },
  { code: "DM", name: "Dominica", dial: 1, currency: "XCD" },
  { code: "DO", name: "Dominican Republic", dial: 1, currency: "DOP" },
  { code: "EC", name: "Ecuador", dial: 593, currency: "USD" },
  { code: "EG", name: "Egypt", dial: 20, currency: "EGP" },
  { code: "SV", name: "El Salvador", dial: 503, currency: "USD" },
  { code: "GQ", name: "Equatorial Guinea", dial: 240, currency: "XAF" },
  { code: "ER", name: "Eritrea", dial: 291, currency: "ERN" },
  { code: "EE", name: "Estonia", dial: 372, currency: "EUR" },
  { code: "SZ", name: "Eswatini", dial: 268, currency: "SZL" },
  { code: "ET", name: "Ethiopia", dial: 251, currency: "ETB" },
  { code: "FK", name: "Falkland Islands (Malvinas)", dial: 500, currency: "FKP" },
  { code: "FO", name: "Faroe Islands", dial: 298, currency: "DKK" },
  { code: "FJ", name: "Fiji", dial: 679, currency: "FJD" },
  { code: "FI", name: "Finland", dial: 358, currency: "EUR" },
  { code: "FR", name: "France", dial: 33, currency: "EUR" },
  { code: "GF", name: "French Guiana", dial: 594, currency: "EUR" },
  { code: "PF", name: "French Polynesia", dial: 689, currency: "XPF" },
  { code: "GA", name: "Gabon", dial: 241, currency: "XAF" },
  { code: "GM", name: "Gambia", dial: 220, currency: "GMD" },
  { code: "GE", name: "Georgia", dial: 995, currency: "GEL" },
  { code: "DE", name: "Germany", dial: 49, currency: "EUR" },
  { code: "GH", name: "Ghana", dial: 233, currency: "GHS" },
  { code: "GI", name: "Gibraltar", dial: 350, currency: "GIP" },
  { code: "GR", name: "Greece", dial: 30, currency: "EUR" },
  { code: "GL", name: "Greenland", dial: 299, currency: "DKK" },
  { code: "GD", name: "Grenada", dial: 1, currency: "XCD" },
  { code: "GP", name: "Guadeloupe", dial: 590, currency: "EUR" },
  { code: "GU", name: "Guam", dial: 1, currency: "USD" },
  { code: "GT", name: "Guatemala", dial: 502, currency: "GTQ" },
  { code: "GG", name: "Guernsey", dial: 44, currency: "GBP" },
  { code: "GN", name: "Guinea", dial: 224, currency: "GNF" },
  { code: "GW", name: "Guinea-Bissau", dial: 245, currency: "XOF" },
  { code: "GY", name: "Guyana", dial: 592, currency: "GYD" },
  { code: "HT", name: "Haiti", dial: 509, currency: "HTG" },
  { code: "VA", name: "Holy See (Vatican City State)", dial: 39, currency: "EUR" },
  { code: "HN", name: "Honduras", dial: 504, currency: "HNL" },
  { code: "HK", name: "Hong Kong", dial: 852, currency: "HKD" },
  { code: "HU", name: "Hungary", dial: 36, currency: "HUF" },
  { code: "IS", name: "Iceland", dial: 354, currency: "ISK" },
  { code: "IN", name: "India", dial: 91, currency: "INR" },
  { code: "ID", name: "Indonesia", dial: 62, currency: "IDR" },
  { code: "IR", name: "Iran, Islamic Republic of", dial: 98, currency: "IRR" },
  { code: "IQ", name: "Iraq", dial: 964, currency: "IQD" },
  { code: "IE", name: "Ireland", dial: 353, currency: "EUR" },
  { code: "IM", name: "Isle of Man", dial: 44, currency: "GBP" },
  { code: "IL", name: "Israel", dial: 972, currency: "ILS" },
  { code: "IT", name: "Italy", dial: 39, currency: "EUR" },
  { code: "JM", name: "Jamaica", dial: 1, currency: "JMD" },
  { code: "JP", name: "Japan", dial: 81, currency: "JPY" },
  { code: "JE", name: "Jersey", dial: 44, currency: "GBP" },
  { code: "JO", name: "Jordan", dial: 962, currency: "JOD" },
  { code: "KZ", name: "Kazakhstan", dial: 7, currency: "KZT" },
  { code: "KE", name: "Kenya", dial: 254, currency: "KES" },
  { code: "KI", name: "Kiribati", dial: 686, currency: "AUD" },
  { code: "KP", name: "Korea, Democratic People's Republic of", dial: 850, currency: "KPW" },
  { code: "KR", name: "Korea, Republic of", dial: 82, currency: "KRW" },
  { code: "KW", name: "Kuwait", dial: 965, currency: "KWD" },
  { code: "KG", name: "Kyrgyzstan", dial: 996, currency: "KGS" },
  { code: "LA", name: "Lao People's Democratic Republic", dial: 856, currency: "LAK" },
  { code: "LV", name: "Latvia", dial: 371, currency: "EUR" },
  { code: "LB", name: "Lebanon", dial: 961, currency: "LBP" },
  { code: "LS", name: "Lesotho", dial: 266, currency: "ZAR" },
  { code: "LR", name: "Liberia", dial: 231, currency: "LRD" },
  { code: "LY", name: "Libya", dial: 218, currency: "LYD" },
  { code: "LI", name: "Liechtenstein", dial: 423, currency: "CHF" },
  { code: "LT", name: "Lithuania", dial: 370, currency: "EUR" },
  { code: "LU", name: "Luxembourg", dial: 352, currency: "EUR" },
  { code: "MO", name: "Macao", dial: 853, currency: "MOP" },
  { code: "MG", name: "Madagascar", dial: 261, currency: "MGA" },
  { code: "MW", name: "Malawi", dial: 265, currency: "MWK" },
  { code: "MY", name: "Malaysia", dial: 60, currency: "MYR" },
  { code: "MV", name: "Maldives", dial: 960, currency: "MVR" },
  { code: "ML", name: "Mali", dial: 223, currency: "XOF" },
  { code: "MT", name: "Malta", dial: 356, currency: "EUR" },
  { code: "MH", name: "Marshall Islands", dial: 692, currency: "USD" },
  { code: "MQ", name: "Martinique", dial: 596, currency: "EUR" },
  { code: "MR", name: "Mauritania", dial: 222, currency: "MRU" },
  { code: "MU", name: "Mauritius", dial: 230, currency: "MUR" },
  { code: "YT", name: "Mayotte", dial: 262, currency: "EUR" },
  { code: "MX", name: "Mexico", dial: 52, currency: "MXN" },
  { code: "FM", name: "Micronesia, Federated States of", dial: 691, currency: "USD" },
  { code: "MD", name: "Moldova, Republic of", dial: 373, currency: "MDL" },
  { code: "MC", name: "Monaco", dial: 377, currency: "EUR" },
  { code: "MN", name: "Mongolia", dial: 976, currency: "MNT" },
  { code: "ME", name: "Montenegro", dial: 382, currency: "EUR" },
  { code: "MS", name: "Montserrat", dial: 1, currency: "XCD" },
  { code: "MA", name: "Morocco", dial: 212, currency: "MAD" },
  { code: "MZ", name: "Mozambique", dial: 258, currency: "MZN" },
  { code: "MM", name: "Myanmar", dial: 95, currency: "MMK" },
  { code: "NA", name: "Namibia", dial: 264, currency: "ZAR" },
  { code: "NR", name: "Nauru", dial: 674, currency: "AUD" },
  { code: "NP", name: "Nepal", dial: 977, currency: "NPR" },
  { code: "NL", name: "Netherlands", dial: 31, currency: "EUR" },
  { code: "NC", name: "New Caledonia", dial: 687, currency: "XPF" },
  { code: "NZ", name: "New Zealand", dial: 64, currency: "NZD" },
  { code: "NI", name: "Nicaragua", dial: 505, currency: "NIO" },
  { code: "NE", name: "Niger", dial: 227, currency: "XOF" },
  { code: "NG", name: "Nigeria", dial: 234, currency: "NGN" },
  { code: "NU", name: "Niue", dial: 683, currency: "NZD" },
  { code: "NF", name: "Norfolk Island", dial: 672, currency: "AUD" },
  { code: "MK", name: "North Macedonia", dial: 389, currency: "MKD" },
  { code: "MP", name: "Northern Mariana Islands", dial: 1, currency: "USD" },
  { code: "NO", name: "Norway", dial: 47, currency: "NOK" },
  { code: "OM", name: "Oman", dial: 968, currency: "OMR" },
  { code: "PK", name: "Pakistan", dial: 92, currency: "PKR" },
  { code: "PW", name: "Palau", dial: 680, currency: "USD" },
  { code: "PS", name: "Palestine, State of", dial: 970, currency: "ILS" },
  { code: "PA", name: "Panama", dial: 507, currency: "PAB" },
  { code: "PG", name: "Papua New Guinea", dial: 675, currency: "PGK" },
  { code: "PY", name: "Paraguay", dial: 595, currency: "PYG" },
  { code: "PE", name: "Peru", dial: 51, currency: "PEN" },
  { code: "PH", name: "Philippines", dial: 63, currency: "PHP" },
  { code: "PL", name: "Poland", dial: 48, currency: "PLN" },
  { code: "PT", name: "Portugal", dial: 351, currency: "EUR" },
  { code: "PR", name: "Puerto Rico", dial: 1, currency: "USD" },
  { code: "QA", name: "Qatar", dial: 974, currency: "QAR" },
  { code: "RO", name: "Romania", dial: 40, currency: "RON" },
  { code: "RU", name: "Russian Federation", dial: 7, currency: "RUB" },
  { code: "RW", name: "Rwanda", dial: 250, currency: "RWF" },
  { code: "RE", name: "Réunion", dial: 262, currency: "EUR" },
  { code: "BL", name: "Saint Barthélemy", dial: 590, currency: "EUR" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dial: 290, currency: "SHP" },
  { code: "KN", name: "Saint Kitts and Nevis", dial: 1, currency: "XCD" },
  { code: "LC", name: "Saint Lucia", dial: 1, currency: "XCD" },
  { code: "MF", name: "Saint Martin (French part)", dial: 590, currency: "EUR" },
  { code: "PM", name: "Saint Pierre and Miquelon", dial: 508, currency: "EUR" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dial: 1, currency: "XCD" },
  { code: "WS", name: "Samoa", dial: 685, currency: "WST" },
  { code: "SM", name: "San Marino", dial: 378, currency: "EUR" },
  { code: "ST", name: "Sao Tome and Principe", dial: 239, currency: "STN" },
  { code: "SA", name: "Saudi Arabia", dial: 966, currency: "SAR" },
  { code: "SN", name: "Senegal", dial: 221, currency: "XOF" },
  { code: "RS", name: "Serbia", dial: 381, currency: "RSD" },
  { code: "SC", name: "Seychelles", dial: 248, currency: "SCR" },
  { code: "SL", name: "Sierra Leone", dial: 232, currency: "SLE" },
  { code: "SG", name: "Singapore", dial: 65, currency: "SGD" },
  { code: "SX", name: "Sint Maarten (Dutch part)", dial: 1, currency: "XCG" },
  { code: "SK", name: "Slovakia", dial: 421, currency: "EUR" },
  { code: "SI", name: "Slovenia", dial: 386, currency: "EUR" },
  { code: "SB", name: "Solomon Islands", dial: 677, currency: "SBD" },
  { code: "SO", name: "Somalia", dial: 252, currency: "SOS" },
  { code: "ZA", name: "South Africa", dial: 27, currency: "ZAR" },
  { code: "SS", name: "South Sudan", dial: 211, currency: "SSP" },
  { code: "ES", name: "Spain", dial: 34, currency: "EUR" },
  { code: "LK", name: "Sri Lanka", dial: 94, currency: "LKR" },
  { code: "SD", name: "Sudan", dial: 249, currency: "SDG" },
  { code: "SR", name: "Suriname", dial: 597, currency: "SRD" },
  { code: "SJ", name: "Svalbard and Jan Mayen", dial: 47, currency: "NOK" },
  { code: "SE", name: "Sweden", dial: 46, currency: "SEK" },
  { code: "CH", name: "Switzerland", dial: 41, currency: "CHF" },
  { code: "SY", name: "Syrian Arab Republic", dial: 963, currency: "SYP" },
  { code: "TW", name: "Taiwan, Province of China", dial: 886, currency: "TWD" },
  { code: "TJ", name: "Tajikistan", dial: 992, currency: "TJS" },
  { code: "TZ", name: "Tanzania, United Republic of", dial: 255, currency: "TZS" },
  { code: "TH", name: "Thailand", dial: 66, currency: "THB" },
  { code: "TL", name: "Timor-Leste", dial: 670, currency: "USD" },
  { code: "TG", name: "Togo", dial: 228, currency: "XOF" },
  { code: "TK", name: "Tokelau", dial: 690, currency: "NZD" },
  { code: "TO", name: "Tonga", dial: 676, currency: "TOP" },
  { code: "TT", name: "Trinidad and Tobago", dial: 1, currency: "TTD" },
  { code: "TN", name: "Tunisia", dial: 216, currency: "TND" },
  { code: "TM", name: "Turkmenistan", dial: 993, currency: "TMT" },
  { code: "TC", name: "Turks and Caicos Islands", dial: 1, currency: "USD" },
  { code: "TV", name: "Tuvalu", dial: 688, currency: "AUD" },
  { code: "TR", name: "Türkiye", dial: 90, currency: "TRY" },
  { code: "UG", name: "Uganda", dial: 256, currency: "UGX" },
  { code: "UA", name: "Ukraine", dial: 380, currency: "UAH" },
  { code: "AE", name: "United Arab Emirates", dial: 971, currency: "AED" },
  { code: "GB", name: "United Kingdom", dial: 44, currency: "GBP" },
  { code: "US", name: "United States", dial: 1, currency: "USD" },
  { code: "UY", name: "Uruguay", dial: 598, currency: "UYU" },
  { code: "UZ", name: "Uzbekistan", dial: 998, currency: "UZS" },
  { code: "VU", name: "Vanuatu", dial: 678, currency: "VUV" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", dial: 58, currency: "VES" },
  { code: "VN", name: "Viet Nam", dial: 84, currency: "VND" },
  { code: "VG", name: "Virgin Islands, British", dial: 1, currency: "USD" },
  { code: "VI", name: "Virgin Islands, U.S.", dial: 1, currency: "USD" },
  { code: "WF", name: "Wallis and Futuna", dial: 681, currency: "XPF" },
  { code: "EH", name: "Western Sahara", dial: 212, currency: "MAD" },
  { code: "YE", name: "Yemen", dial: 967, currency: "YER" },
  { code: "ZM", name: "Zambia", dial: 260, currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", dial: 263, currency: "USD" },
  { code: "AX", name: "Åland Islands", dial: 358, currency: "EUR" },];

export const COUNTRIES: CountryInfo[] = COUNTRY_DATA.map((c) => ({ ...c, flag: flagEmoji(c.code) }));
export const DEFAULT_COUNTRY = "US";

// Validity check used by signup/profile forms (returns undefined when invalid).
export function countryByCode(code: string | null | undefined): CountryInfo | undefined {
  return COUNTRIES.find((c) => c.code === (code ?? "").toUpperCase());
}

export function isCountryCode(value: string | null | undefined): boolean {
  return !!countryByCode(value);
}

// Always returns a CountryInfo (falls back to the default country) - safe
// for display contexts like trader/bot cards where the field should never
// be empty, but defensively handles stale/missing data anyway.
export function countryInfo(code: string | null | undefined): CountryInfo {
  return countryByCode(code) ?? countryByCode(DEFAULT_COUNTRY)!;
}

export function currencyForCountry(code: string | null | undefined): string {
  return countryByCode(code)?.currency ?? "USD";
}
