import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1100 } });
page.setDefaultTimeout(10000);
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.click(".profile-button");
await page.click("text=Sign in");
await page.waitForSelector(".auth-modal");
await page.fill(".auth-modal input:not([type=password])", "admin@nexatrade.test");
await page.fill(".auth-modal input[type=password]", "adminpass123");
await page.click(".auth-modal button.primary-btn");
await page.waitForTimeout(1200);
await page.goto("http://localhost:3000/admin", { waitUntil: "networkidle" });
await page.waitForTimeout(1000);
await page.click('.nav-item:has-text("Manage users")');
await page.waitForTimeout(800);
page.on("console", msg => console.log("PAGE LOG:", msg.text()));
page.on("requestfinished", req => { if (req.url().includes("/api/admin/users/")) console.log("REQ:", req.url()); });
await page.fill('input[placeholder="Search by name or email…"]', "jane@nexatrade.test");
await page.waitForTimeout(600);
await page.waitForSelector('button:has-text("Manage")');
const btn = page.locator('table button:text-is("Manage")').first();
console.log("btn count", await page.locator('table button:text-is("Manage")').count());
await btn.click({ force: true });
await page.waitForTimeout(2500);
await page.screenshot({ path: "/tmp/shot-admin-user.png", fullPage: true });
await browser.close();
console.log("done");
